title: OO-programering
description: Objektorientering
template:
  repo: oo-programering-template
  name: oo-programering
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
